/**
 * Baked header banner — generated by `npm run bake:header`. Do not edit by hand.
 *
 * 5 finished-ANSI lines of Unicode quadrant cells, folded by
 * chafa (`--symbols quad`) from the 48×36 sprite bitmap that
 * `decode:chart` extracts from the source chart `packages/header/assets/132_1_mae_1_No.png` (ADR 0012). The
 * art is scaled to a fixed 5-row banner whose width preserves the source aspect
 * ratio on a ~2:1 character grid: width is nearest-neighbour resampled (hard
 * alpha preserved, so the float survives), height is averaging-resampled
 * (ADR 0008, reopening ADR 0007). Each cell carries one truecolor
 * foreground + one truecolor background and a glyph from the 16-member
 * block-quadrant set; transparent source cells emit no background SGR, so the
 * sprite floats on the terminal background (ADR 0003 invariant, preserved).
 * Imported by the header at runtime; the shipped extension never decodes the
 * source image. The mirror orientation is chosen at bake time (flip on — mirrored),
 * so the render path prints the lines as-is with no runtime flip (ADR 0006).
 * Re-run the regen script and re-commit this file when the source image changes.
 */

export const BANNER: string[] = [
	"\u001b[0m \u001b[38;2;0;0;0m \u001b[38;2;79;67;94m▗\u001b[38;2;44;39;51;48;2;158;128;193m▀\u001b[38;2;86;78;94;48;2;183;143;222m▀\u001b[38;2;184;145;214;48;2;81;73;89m▖\u001b[0m\u001b[7m\u001b[38;2;93;84;106m▀\u001b[0m\u001b[38;2;185;145;215;48;2;80;73;89m▗\u001b[38;2;86;78;94;48;2;196;153;227m▀\u001b[38;2;163;131;196;48;2;56;50;64m▖\u001b[0m\u001b[38;2;31;31;31m▖  \u001b[0m",
	" \u001b[38;2;18;18;18m▐\u001b[38;2;140;115;169;48;2;62;54;74m▐\u001b[38;2;180;141;220;48;2;182;142;222m▘\u001b[38;2;186;146;224;48;2;183;143;223m▝\u001b[38;2;168;134;203;48;2;187;146;224m▝\u001b[38;2;163;131;199;48;2;183;143;223m▀\u001b[38;2;215;169;233;48;2;183;144;218m▝\u001b[38;2;222;174;238;48;2;196;153;228m▀\u001b[38;2;128;107;154;48;2;175;139;211m▝\u001b[38;2;58;53;66;48;2;104;88;125m▝\u001b[38;2;45;45;45;48;2;25;25;25m▗\u001b[0m \u001b[0m",
	"\u001b[38;2;106;89;122;48;2;60;60;60m▐\u001b[38;2;166;129;202;48;2;171;134;208m▝\u001b[38;2;136;109;168;48;2;161;127;197m▐\u001b[38;2;137;112;168;48;2;144;119;176m▝\u001b[38;2;75;59;91;48;2;132;110;160m▀\u001b[38;2;130;108;159;48;2;163;129;199m▗\u001b[48;2;165;131;201m▗\u001b[48;2;163;129;199m▖\u001b[38;2;75;59;91;48;2;132;110;160m▀\u001b[38;2;125;96;157;48;2;139;115;171m▝\u001b[38;2;119;89;151;48;2;155;124;190m▘\u001b[38;2;166;129;202;48;2;171;134;208m▘\u001b[38;2;60;60;60;48;2;91;80;102m▝\u001b[0m",
	"\u001b[38;2;76;68;87;48;2;44;44;44m▐\u001b[38;2;111;96;132;48;2;142;118;174m▘\u001b[48;2;143;119;175m \u001b[38;2;134;112;164m▝\u001b[38;2;92;83;106m▀\u001b[38;2;64;54;76m▀\u001b[38;2;62;52;74m▀\u001b[38;2;64;54;76m▀\u001b[38;2;92;82;106m▀\u001b[38;2;134;112;164m▘ \u001b[38;2;111;96;132;48;2;142;118;174m▝\u001b[38;2;86;75;102;48;2;51;50;53m▖\u001b[0m",
	"\u001b[38;2;49;44;55m▝\u001b[38;2;84;75;97m▀\u001b[38;2;126;106;152;48;2;67;64;72m▀\u001b[38;2;143;119;175;48;2;76;71;83m▀\u001b[48;2;39;34;46m▀\u001b[48;2;37;32;44m▀▀▀\u001b[48;2;39;34;46m▀\u001b[48;2;76;71;83m▀\u001b[38;2;126;106;152;48;2;67;64;72m▀\u001b[0m\u001b[7m\u001b[38;2;72;66;81m▗\u001b[0m \u001b[0m",
];
