/**
 * Baked header banner — generated by `npm run bake:header`. Do not edit by hand.
 *
 * 5 finished-ANSI lines of Unicode quadrant cells, folded by
 * chafa (`--symbols quad`) from the 21×20 sprite bitmap that
 * `decode:chart` extracts from the source chart `packages/header/assets/pokemon.png` (ADR 0012). The
 * art is scaled to a fixed 5-row banner whose width preserves the source aspect
 * ratio on a ~2:1 character grid: width is nearest-neighbour resampled (hard
 * alpha preserved, so the float survives), height is averaging-resampled
 * (ADR 0008, reopening ADR 0007). Each cell carries one truecolor
 * foreground + one truecolor background and a glyph from the 16-member
 * block-quadrant set; transparent source cells emit no background SGR, so the
 * sprite floats on the terminal background (ADR 0003 invariant, preserved).
 * Imported by the header at runtime; the shipped extension never decodes the
 * source image. The mirror orientation is chosen at bake time (flip on — mirrored),
 * so the render path prints the lines as-is with no runtime flip (ADR 0006).
 * Re-run the regen script and re-commit this file when the source image changes.
 */

export const BANNER: string[] = [
	"\u001b[0m\u001b[38;2;159;133;30m▗\u001b[38;2;35;30;5;48;2;204;173;41m▀\u001b[0m\u001b[38;2;143;123;25m▖\u001b[38;2;4;4;0m▖  \u001b[38;2;22;18;1m▗\u001b[38;2;0;0;0;48;2;121;101;22m▀\u001b[0m\u001b[38;2;49;40;6m▖  \u001b[0m",
	"\u001b[38;2;140;117;25m▝\u001b[38;2;183;153;37;48;2;46;38;6m▀\u001b[38;2;185;155;38;48;2;199;168;40m▖\u001b[38;2;39;32;4;48;2;167;140;33m▝\u001b[38;2;51;44;5;48;2;155;133;26m▘\u001b[38;2;104;90;17;48;2;233;202;46m▀\u001b[0m\u001b[7m\u001b[38;2;159;137;28m▀\u001b[0m\u001b[38;2;131;110;21;48;2;220;189;43m▘\u001b[38;2;67;56;9;48;2;232;200;46m▀\u001b[0m\u001b[38;2;178;153;32m▖ \u001b[0m",
	" \u001b[38;2;57;47;6m▝\u001b[38;2;143;119;26;48;2;176;147;35m▖\u001b[38;2;54;46;6;48;2;138;115;25m▗\u001b[38;2;62;53;7;48;2;195;169;36m▀\u001b[38;2;216;185;42;48;2;243;210;49m▘\u001b[38;2;177;97;54;48;2;221;178;54m▗\u001b[38;2;237;215;114;48;2;207;178;57m▀\u001b[38;2;237;206;47;48;2;244;212;48m▗\u001b[38;2;213;185;40;48;2;128;110;20m▀\u001b[0m\u001b[7m\u001b[38;2;75;64;10m▐\u001b[0m",
	" \u001b[38;2;0;0;0m \u001b[38;2;127;83;25m▝\u001b[38;2;81;62;11;48;2;172;135;33m▖\u001b[38;2;217;177;46;48;2;240;208;48m▘\u001b[38;2;183;158;31;48;2;223;192;43m▗\u001b[38;2;159;135;27;48;2;201;139;48m▗\u001b[38;2;234;198;48;48;2;191;160;39m▀\u001b[38;2;188;160;36;48;2;51;43;7m▀\u001b[0m\u001b[38;2;79;65;10m▀\u001b[38;2;52;43;6m▘\u001b[0m",
	" \u001b[38;2;0;0;0m  \u001b[38;2;100;87;15m▝\u001b[38;2;240;208;47;48;2;109;95;19m▀\u001b[38;2;234;204;46;48;2;54;47;8m▀\u001b[0m\u001b[38;2;151;129;28m▀\u001b[38;2;135;113;23m▀\u001b[38;2;51;41;5m▘  \u001b[0m",
];
