/**
 * Baked header sprite — generated by `npm run bake:sprite`. Do not edit by hand.
 *
 * 6 finished-ANSI lines of Unicode quadrant cells, folded by
 * chafa (`--symbols quad`) from the 160×120 sprite bitmap that
 * `decode:chart` extracts from the source chart `packages/header/assets/132_1_mae_1_No.png` (ADR 0012). The
 * art is scaled to a fixed 6-row sprite whose width preserves the source aspect
 * ratio on a ~2:1 character grid: width is nearest-neighbour resampled (hard
 * alpha preserved, so the float survives), height is averaging-resampled
 * (ADR 0008, reopening ADR 0007). Each cell carries one truecolor
 * foreground + one truecolor background and a glyph from the 16-member
 * block-quadrant set; transparent source cells emit no background SGR, so the
 * sprite floats on the terminal background (ADR 0003 invariant, preserved).
 * Imported by the header at runtime; the shipped extension never decodes the
 * source image. The mirror orientation is chosen at bake time (flip on — mirrored),
 * so the render path prints the lines as-is with no runtime flip (ADR 0006).
 * Re-run the regen script and re-commit this file when the source image changes.
 */

export const SPRITE: string[] = [
	"\u001b[0m \u001b[38;2;0;0;0m \u001b[0m \u001b[38;2;62;52;76m▗\u001b[38;2;18;18;18;48;2;146;120;178m▀\u001b[38;2;63;63;63;48;2;182;142;221m▀\u001b[38;2;62;62;62;48;2;176;138;215m▀\u001b[0m\u001b[7m\u001b[38;2;73;69;77m▀\u001b[0m\u001b[38;2;83;75;91m▗\u001b[38;2;62;62;62;48;2;176;138;215m▀\u001b[38;2;63;63;63;48;2;182;142;221m▀\u001b[38;2;18;18;18;48;2;146;120;178m▀\u001b[0m\u001b[38;2;10;10;10m▗\u001b[0m \u001b[38;2;34;34;34m  \u001b[0m",
	"  \u001b[38;2;67;56;82m▗\u001b[38;2;83;75;90;48;2;147;121;180m▀\u001b[38;2;179;140;218;48;2;182;142;222m▘\u001b[38;2;190;149;226;48;2;183;143;223m▝\u001b[38;2;216;170;234m▀\u001b[38;2;148;122;179m▀\u001b[38;2;148;122;178;48;2;185;144;224m▀\u001b[38;2;212;168;230;48;2;221;173;238m▘\u001b[38;2;221;173;238;48;2;222;174;238m▝\u001b[38;2;180;141;219;48;2;192;150;226m▐\u001b[38;2;83;75;91;48;2;147;121;180m▀\u001b[0m\u001b[38;2;9;9;9m▗\u001b[0m \u001b[38;2;33;33;33m \u001b[0m",
	"\u001b[38;2;116;97;136m▗\u001b[38;2;58;58;58;48;2;182;142;222m▀\u001b[38;2;39;33;46;48;2;174;135;213m▀\u001b[38;2;147;121;180;48;2;117;86;149m▀\u001b[38;2;182;142;222;48;2;134;111;165m▀\u001b[38;2;183;143;223;48;2;42;35;51m▀\u001b[38;2;176;137;214;48;2;183;143;223m▖  ▗\u001b[38;2;183;143;223;48;2;43;35;51m▀\u001b[38;2;182;142;222;48;2;134;111;165m▀\u001b[38;2;147;121;180;48;2;117;86;149m▀\u001b[38;2;39;34;47;48;2;174;135;213m▀\u001b[38;2;58;58;58;48;2;182;142;222m▀\u001b[0m\u001b[7m\u001b[38;2;90;80;100m▀\u001b[0m",
	"\u001b[38;2;116;97;136m▝\u001b[38;2;182;142;222;48;2;79;74;86m▀\u001b[38;2;178;140;217;48;2;142;118;174m▀\u001b[38;2;144;120;177;48;2;143;119;175m▘\u001b[38;2;131;110;159m▗\u001b[38;2;143;119;175;48;2;64;63;66m▀\u001b[48;2;13;13;13m▀\u001b[48;2;9;9;9m▀▀\u001b[48;2;12;12;12m▀\u001b[48;2;64;63;65m▀\u001b[38;2;130;109;158;48;2;143;119;175m▖\u001b[38;2;144;120;177m▝\u001b[38;2;178;140;216;48;2;142;118;174m▀\u001b[38;2;182;142;222;48;2;79;74;86m▀\u001b[0m\u001b[38;2;90;80;100m▀\u001b[0m",
	"\u001b[38;2;86;74;102;48;2;36;36;36m▐\u001b[48;2;142;118;174m \u001b[48;2;143;119;175m            \u001b[48;2;142;118;174m \u001b[38;2;36;36;36;48;2;86;74;102m▐\u001b[0m",
	" \u001b[7m\u001b[38;2;28;28;28m▗\u001b[0m\u001b[38;2;91;82;104m▝\u001b[38;2;142;118;173;48;2;63;63;63m▀\u001b[38;2;143;119;175;48;2;60;60;60m▀\u001b[48;2;11;11;11m▀\u001b[48;2;9;9;9m▀▀▀▀\u001b[48;2;11;11;11m▀\u001b[48;2;60;60;60m▀\u001b[38;2;142;118;173;48;2;63;63;63m▀\u001b[0m\u001b[38;2;77;72;84m▀\u001b[38;2;9;9;9m▝\u001b[0m \u001b[0m",
];
